# Generated by Django 3.1.2 on 2020-10-24 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='juego',
            fields=[
                ('id_juego', models.UUIDField(default=uuid.uuid4, help_text='Atributo unico para este juego en particular', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descipcion', models.TextField(max_length=1000)),
                ('precio', models.CharField(max_length=6)),
                ('status', models.CharField(blank=True, choices=[('S', 'Steam'), ('O', 'Origin')], default='S', help_text='Plataforma del juego', max_length=1)),
            ],
        ),
    ]
