# Generated by Django 3.1.2 on 2020-11-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='id_juego',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='juego',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Steam'), ('O', 'Origin')], default='S', help_text='Plataforma del juego', max_length=100),
        ),
    ]
