# Generated by Django 3.1.2 on 2020-11-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20201105_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='id_juego',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
