# Generated by Django 3.1.2 on 2020-11-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20201105_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
