# Generated by Django 3.1.2 on 2020-11-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20201105_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='descripcion',
            new_name='descipcion',
        ),
    ]
