# Generated by Django 3.1.2 on 2020-11-05 14:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_auto_20201105_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='id_juego',
            field=models.UUIDField(default=uuid.uuid4, help_text='Atributo unico para este juego en particular', primary_key=True, serialize=False),
        ),
    ]
