# Generated by Django 3.1.2 on 2020-11-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_auto_20201105_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='status',
            field=models.CharField(blank=True, choices=[('S', 'Steam'), ('O', 'Origin')], default='S', help_text='Plataforma del juego', max_length=1),
        ),
    ]
