# Generated by Django 3.1.2 on 2020-11-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_auto_20201105_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='status',
            new_name='plataforma',
        ),
    ]
