# Generated by Django 3.1.2 on 2020-11-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_auto_20201105_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='plataforma',
            new_name='status',
        ),
    ]
